# Generated by Django 5.2.17 on 2026-09-30 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("cargo", models.CharField(max_length=80)),
                ("setor", models.CharField(max_length=80)),
                ("data_entrada", models.DateField()),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "colaboradores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Sistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
                ("descricao", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("acao", models.CharField(max_length=40)),
                ("colaborador", models.CharField(max_length=120)),
                ("sistema", models.CharField(blank=True, max_length=80)),
                (
                    "feito_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Acesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("leitura", "Só leitura"),
                            ("edicao", "Leitura e edição"),
                            ("admin", "Administrador"),
                        ],
                        default="leitura",
                        max_length=10,
                    ),
                ),
                ("concedido_em", models.DateTimeField(auto_now_add=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acessos",
                        to="acessos.colaborador",
                    ),
                ),
                (
                    "sistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acessos",
                        to="acessos.sistema",
                    ),
                ),
            ],
            options={
                "unique_together": {("colaborador", "sistema")},
            },
        ),
    ]
